### ISSUE TITLE
是否有支持 h264 裸流的 pts dts 计算?

### ISSUE THREAD

**Issue by foobra** [CmST0us/VideoCodecKit#1]
最近在研究这一块, pts dts 从 h264中裸流, 需要挨着 nalu 去扣出来计算, 请问一下有什么好的资料讲这一块的吗?

**Comment by foobra** [comment]
我自己从 I/P/B 帧和帧率计算出来了.

**Comment by CmST0us** [comment]
你好
不好意思现在才看到这个Issue. 
对于h264裸流，如果目的是显示裸流的话，一般关心pts就可以了。由于h264裸流本身不带pts, 可以参考
https://github.com/CmST0us/VideoCodecKit/blob/master/VideoCodecKit/VideoCodecKit/FrameParser/H264/VCH264Frame%2BFFmpeg.m 中22行，使用output_picture_number，结合帧率可以计算出pts。
方法和您的实现大致一样。

**Comment by CmST0us** [comment]
> 我自己从 I/P/B 帧和帧率计算出来了.

你好
不好意思现在才看到这个Issue.
对于h264裸流，如果目的是显示裸流的话，一般关心pts就可以了。由于h264裸流本身不带pts, 可以参考
https://github.com/CmST0us/VideoCodecKit/blob/master/VideoCodecKit/VideoCodecKit/FrameParser/H264/VCH264Frame%2BFFmpeg.m 中22行，使用output_picture_number，结合帧率可以计算出pts。
方法和您的实现大致一样。
