### ISSUE TITLE
支持本地视频么？

### ISSUE THREAD

**Issue by winterwd** [CmST0us/VideoCodecKit#3]
这个支持本地视频么，包含MP4，H.264，H.265等

**Comment by CmST0us** [comment]
支持h264 h265裸流播放，mp4暂时不支持可考虑用系统提供的AVPlayer

**Comment by yunjuanyunshu2019** [comment]
用WebSocket 接受的flv封装的h264数据,播放会绿屏,请问是怎么回事

**Comment by CmST0us** [comment]
> 用WebSocket 接受的flv封装的h264数据,播放会绿屏,请问是怎么回事

部分绿还是全部？可以给图片看一下吗？
检查一下传输的flv是否正确，IDR帧是否给解码器喂了PPS SPS

**Comment by yunjuanyunshu2019** [comment]
上边1/5有图像,下边4/5是绿屏,同样的数据安卓的手机没有绿屏

**Comment by CmST0us** [comment]
处理flv的时候，解flv解对了吗，送入解码器前的数据双端比对过内容和长度一致吗？
可以的话给发一下代码片段

**Comment by yunjuanyunshu2019** [comment]
模拟器可以播放，真机不行------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;eki&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月23日(星期二) 下午2:19
收件人:&nbsp;&quot;CmST0us/VideoCodecKit&quot;<VideoCodecKit@noreply.github.com&gt;;
抄送:&nbsp;&quot;yunjuanyunshu2019&quot;<1424695927@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [CmST0us/VideoCodecKit] 支持本地视频么？ (#3)
